-- MySQL Script generated by MySQL Workbench
-- Seg 23 Mai 2016 13:38:13 BRT
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `biblioteca` ;

-- -----------------------------------------------------
-- Schema biblioteca
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
SHOW WARNINGS;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `biblioteca`.`assunto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`assunto` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `biblioteca`.`assunto` (
  `idassunto` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idassunto`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `biblioteca`.`autor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`autor` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `biblioteca`.`autor` (
  `idautor` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`idautor`))
ENGINE = InnoDB
AUTO_INCREMENT = 60
DEFAULT CHARACTER SET = latin1
COMMENT = 'autores dos livros';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `biblioteca`.`chefes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`chefes` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `biblioteca`.`chefes` (
  `idchefes` INT(11) NOT NULL,
  `nome` VARCHAR(60) NOT NULL,
  PRIMARY KEY (`idchefes`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Chefes dos departamentos';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `biblioteca`.`departamento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`departamento` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `biblioteca`.`departamento` (
  `idDepartamento` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `idchefes` INT(11) NOT NULL,
  PRIMARY KEY (`idDepartamento`, `idchefes`),
  CONSTRAINT `fk_departamento_chefes1`
    FOREIGN KEY (`idchefes`)
    REFERENCES `biblioteca`.`chefes` (`idchefes`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = latin1
COMMENT = 'Departamento do funcionário que concedeu o empréstimo.\nDeyvison Rodrigo';

SHOW WARNINGS;
CREATE INDEX `fk_departamento_chefes1_idx` ON `biblioteca`.`departamento` (`idchefes` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `biblioteca`.`editora`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`editora` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `biblioteca`.`editora` (
  `ideditora` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL DEFAULT NULL,
  `cidade` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`ideditora`))
ENGINE = InnoDB
AUTO_INCREMENT = 3
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `biblioteca`.`obra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`obra` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `biblioteca`.`obra` (
  `idobra` INT(11) NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(60) NOT NULL,
  `ano_publicacao` VARCHAR(7) NOT NULL DEFAULT '00/0000',
  `ideditora` INT(11) NOT NULL,
  `idautor` INT(11) NOT NULL,
  `idassunto` INT(11) NOT NULL,
  PRIMARY KEY (`idobra`, `ideditora`, `idautor`, `idassunto`),
  CONSTRAINT `fk_obra_editora1`
    FOREIGN KEY (`ideditora`)
    REFERENCES `biblioteca`.`editora` (`ideditora`),
  CONSTRAINT `fk_obra_autor1`
    FOREIGN KEY (`idautor`)
    REFERENCES `biblioteca`.`autor` (`idautor`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT,
  CONSTRAINT `fk_obra_assunto1`
    FOREIGN KEY (`idassunto`)
    REFERENCES `biblioteca`.`assunto` (`idassunto`)
    ON DELETE RESTRICT
    ON UPDATE RESTRICT)
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8;

SHOW WARNINGS;
CREATE INDEX `fk_obra_editora1_idx` ON `biblioteca`.`obra` (`ideditora` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_obra_autor1_idx` ON `biblioteca`.`obra` (`idautor` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_obra_assunto1_idx` ON `biblioteca`.`obra` (`idassunto` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `biblioteca`.`situacao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`situacao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `biblioteca`.`situacao` (
  `idsituacao` INT(11) NOT NULL AUTO_INCREMENT,
  `descricao` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idsituacao`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = latin1
COMMENT = 'Situação:\n1 -> Disponivel\n2 -> Emprestado\n3 -> Em Manutencao';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `biblioteca`.`exemplar`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`exemplar` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `biblioteca`.`exemplar` (
  `idexemplar` INT(11) NOT NULL AUTO_INCREMENT,
  `data_aquisicao` DATE NOT NULL,
  `idobra` INT(11) NOT NULL,
  `idsituacao` INT(11) NOT NULL,
  PRIMARY KEY (`idexemplar`, `idobra`, `idsituacao`),
  CONSTRAINT `fk_exemplar_obra1`
    FOREIGN KEY (`idobra`)
    REFERENCES `biblioteca`.`obra` (`idobra`),
  CONSTRAINT `fk_exemplar_situacao1`
    FOREIGN KEY (`idsituacao`)
    REFERENCES `biblioteca`.`situacao` (`idsituacao`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_exemplar_obra1_idx` ON `biblioteca`.`exemplar` (`idobra` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_exemplar_situacao1_idx` ON `biblioteca`.`exemplar` (`idsituacao` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `biblioteca`.`funcionario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`funcionario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `biblioteca`.`funcionario` (
  `idfuncionario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(60) NOT NULL,
  `salario` DOUBLE NULL DEFAULT NULL,
  `idDepartamento` INT(11) NOT NULL,
  PRIMARY KEY (`idfuncionario`, `idDepartamento`),
  CONSTRAINT `fk_funcionario_departamento1`
    FOREIGN KEY (`idDepartamento`)
    REFERENCES `biblioteca`.`departamento` (`idDepartamento`))
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = latin1
COMMENT = 'Funcionário ligado a Devolução..\nDeyvison Rodrigo';

SHOW WARNINGS;
CREATE INDEX `fk_funcionario_departamento1_idx` ON `biblioteca`.`funcionario` (`idDepartamento` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `biblioteca`.`usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`usuario` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `biblioteca`.`usuario` (
  `idusuario` INT(11) NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`idusuario`))
ENGINE = InnoDB
AUTO_INCREMENT = 512
DEFAULT CHARACTER SET = latin1
COMMENT = 'usuarios do sistema de bibliateca: \nauthor: deyvison Rodrigo';

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `biblioteca`.`emprestimo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`emprestimo` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `biblioteca`.`emprestimo` (
  `idemprestimo` INT(11) NOT NULL AUTO_INCREMENT,
  `idusuario` INT(11) NOT NULL,
  `idexemplar` INT(11) NOT NULL,
  `data_emprestimo` DATE NOT NULL,
  `previsao_devolucao` DATE NOT NULL,
  `idfuncionario` INT(11) NOT NULL,
  PRIMARY KEY (`idemprestimo`, `idusuario`, `idexemplar`, `idfuncionario`),
  CONSTRAINT `fk_emprestimo_exemplar1`
    FOREIGN KEY (`idexemplar`)
    REFERENCES `biblioteca`.`exemplar` (`idexemplar`),
  CONSTRAINT `fk_emprestimo_funcionario1`
    FOREIGN KEY (`idfuncionario`)
    REFERENCES `biblioteca`.`funcionario` (`idfuncionario`),
  CONSTRAINT `fk_emprestimo_usuario1`
    FOREIGN KEY (`idusuario`)
    REFERENCES `biblioteca`.`usuario` (`idusuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COMMENT = 'Tabela de empréstimos\nDeyvison Rodrigo';

SHOW WARNINGS;
CREATE INDEX `fk_emprestimo_usuario1_idx` ON `biblioteca`.`emprestimo` (`idusuario` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_emprestimo_exemplar1_idx` ON `biblioteca`.`emprestimo` (`idexemplar` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_emprestimo_funcionario1_idx` ON `biblioteca`.`emprestimo` (`idfuncionario` ASC);

SHOW WARNINGS;

-- -----------------------------------------------------
-- Table `biblioteca`.`devolucao`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `biblioteca`.`devolucao` ;

SHOW WARNINGS;
CREATE TABLE IF NOT EXISTS `biblioteca`.`devolucao` (
  `iddevolucao` INT(11) NOT NULL AUTO_INCREMENT,
  `idfuncionario` INT(11) NOT NULL,
  `idemprestimo` INT(11) NOT NULL,
  PRIMARY KEY (`iddevolucao`, `idfuncionario`, `idemprestimo`),
  CONSTRAINT `fk_devolucao_emprestimo1`
    FOREIGN KEY (`idemprestimo`)
    REFERENCES `biblioteca`.`emprestimo` (`idemprestimo`),
  CONSTRAINT `fk_devolucao_funcionario1`
    FOREIGN KEY (`idfuncionario`)
    REFERENCES `biblioteca`.`funcionario` (`idfuncionario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;

SHOW WARNINGS;
CREATE INDEX `fk_devolucao_funcionario1_idx` ON `biblioteca`.`devolucao` (`idfuncionario` ASC);

SHOW WARNINGS;
CREATE INDEX `fk_devolucao_emprestimo1_idx` ON `biblioteca`.`devolucao` (`idemprestimo` ASC);

SHOW WARNINGS;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

